## 1.2.1 Known Statistics---Computation for matrix inversion

In [5]:
import numpy as np
R_x = np.array([5,-1,-2,-1,5,-1,-2,-1,5]).reshape((3,3))
print(f'R_x:\n{R_x}')
print(f'inverted R_x:\n {np.linalg.inv(R_x)}')

R_x:
[[ 5 -1 -2]
 [-1  5 -1]
 [-2 -1  5]]
inverted R_x:
 [[0.26373626 0.07692308 0.12087912]
 [0.07692308 0.23076923 0.07692308]
 [0.12087912 0.07692308 0.26373626]]
